### ISSUE TITLE
Saidil on üles seatud A-B testimine (nt Google Analytcs’i kaudu).

### ISSUE THREAD

**Issue by carlmaask** [carlmaask/veebiarendus#16]

**Comment by ainarend** [comment]
![ab1](https://cloud.githubusercontent.com/assets/22946995/20876857/80a8c5aa-bacd-11e6-99e2-436d03ead7b1.png)
![ab2](https://cloud.githubusercontent.com/assets/22946995/20876858/80a92838-bacd-11e6-9716-86b1823ebdd1.png)
