### ISSUE TITLE
Esilehel pildi avamine läheb mingil põhjusel läbi wp-admini.

### ISSUE THREAD

**Issue by carlmaask** [carlmaask/veebiarendus#19]
Kui esilehel pildi suumile vajutad läheb ta läbi wp-admini ning saab meie lukustatud alamkausta käest tala.

**Comment by ainarend** [comment]
commented out line 43 from /sauron/inc/js/lightbox.js:

`this.createpopup(admin_ajax_url, data, 0, width, height,  1, 'testpopup', 5);`

**Comment by carlmaask** [comment]
Üleliigne komponent eemaldatud.
