### ISSUE TITLE
Saidile on lisatud Google Analytics.

### ISSUE THREAD

**Issue by carlmaask** [carlmaask/veebiarendus#6]

**Comment by ainarend** [comment]
Once we have the theme down, then:

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-88116622-1', 'auto');
  ga('send', 'pageview');

</script>

**Comment by carlmaask** [comment]
Lisatud header ja footer plugina kaudu.
