### ISSUE TITLE
Saidil on erilahendusena korralikud Not Found 404 ja Site Down 500 lehed (mõtteid). Leht on tavaliselt maas siis kui arendaja midagi uuendab või parandab. 

### ISSUE THREAD

**Issue by carlmaask** [carlmaask/veebiarendus#9]

**Comment by ainarend** [comment]
https://github.com/AndiDittrich/HttpErrorPages

**Comment by ainarend** [comment]
https://codex.wordpress.org/Creating_an_Error_404_Page

Help Your Server Find the 404 Page

**Comment by ainarend** [comment]
Using theme's native 404 error page. 

Added 500 page from the HttpErrorPages git.
